name: Refresh examples

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  Refresh:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        branch:
        - Electron-quick-start
        - Flutter-demo
        - GTK3-adventure
        - GTK3-mastermind
        - Qt5-bomber-first-try
        - Qt6-example
        - SDL2-neverputt
        - native-glmark2
        - x11-glxgears

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        # check out the target branch
        ref: ${{ matrix.branch }}
        # we need all the history to rebase
        fetch-depth: 0

    - name: Update ${{ matrix.branch }}
      env:
        GIT_AUTHOR_NAME: "Mir CI Bot"
        GIT_AUTHOR_EMAIL: "mir-ci-bot@canonical.com"
        GIT_COMMITTER_NAME: "Mir CI Bot"
        GIT_COMMITTER_EMAIL: "mir-ci-bot@canonical.com"
      run: |
        git fetch origin ${{ github.event_name == 'pull_request' && github.base_ref || github.ref }}
        git rebase FETCH_HEAD
        if ${{ matrix.branch == 'Qt5-bomber-first-try' }}; then
          # there's a "second stage" here
          git checkout Qt5-bomber
          git rebase Qt5-bomber-first-try
        fi

    - name: Build the snap
      uses: canonical/actions/build-snap@release

    - name: Push upstream
      if: ${{ github.event_name == 'push' }}
      run: |
        git push --force origin ${{ matrix.branch }}
        if ${{ matrix.branch == 'Qt5-bomber-first-try' }}; then
          git push --force origin Qt5-bomber
        fi
